---
title: "Causal Inference Introduction"
author: "Gray Stanton and Austin Ellingworth"
date: 2020-10-21
publishDate: "`r format(Sys.time(), '%Y-%m-%d')`"
summary: "We will discuss two papers introducing overviews of the concepts of causal inference: \"Causal diagrams for empirical research\" (Pearl, 1995) and \"Causal Inference Using Potential Outcomes: Design, Modeling, Decisions\" (Rubin, 2005)"
paper: ["https://www.jstor.org/stable/pdf/27590541.pdf?casa_token=mwnYLYO1ZjgAAAAA:QP3fr5sUHBCVcvv20Avsw2U5CFLnWEVyYsDZtbi4ekmVxXwTwVGRCh7RobYl_Z2azijj1sKJ0hRmnndVD2ehb6euwgXLEsDwA6AO5LjbI_yVV5fbGBA", "https://academic.oup.com/biomet/article-pdf/82/4/669/698263/82-4-669.pdf?casa_token=mXTSuWdeV7YAAAAA:Lvs_RVu18N6LgUDUm68FJ6t6IbF2FApaTvHCjPzR4d_g6qmU1OmjJyFXniofSEsiM5Qmwg6BMd-N"]
supplement: []
slides: "/slides/2020_10_21/causal_notes_combined.pdf"
---

Abstracts from the papers:

Rubin (2005)

> Causal effects are defined as comparisons of potential outcomes under different treatments on a common set of units. Observed values of the potential outcomes are revealed by the assignment mechanism--a probabilistic model for the treatment each unit receives as a function of covariates and potential outcomes. Fisher made tremendous contributions to causal inference through his work on the design of randomized experiments, but the potential outcomes perspective applies to other complex experiments and nonrandomized studies as well. As noted by Kempthorne in his 1976 discussion of Savage's Fisher lecture, Fisher never bridged his work on experimental design and his work on parametric modeling, a bridge that appears nearly automatic with an appropriate view of the potential outcomes framework, where the potential outcomes and covariates are given a Bayesian distribution to complete the model specification. Also, this framework crisply separates scientific inference for causal effects and decisions based on such inference, a distinction evident in Fisher's discussion of tests of significance versus tests in an accept/reject framework. But Fisher never used the potential outcomes framework, originally proposed by Neyman in the context of randomized experiments, and as a result he provided generally flawed advice concerning the use of the analysis of covariance to adjust for posttreatment concomitants in randomized trials.

Pearl (1995)


> The primary aim of this paper is to show how graphical models can be used as a mathematical language for integrating statistical and subject-matter information. In particular, the paper develops a principled, nonparametric framework for causal inference, in which diagrams are queried to determine if the assumptions available are sufficient for identifying causal effects from nonexperimental data. If so the diagrams can be queried to produce mathematical expressions for causal effects in terms of observed distributions; otherwise, the diagrams can be queried to suggest additional observations or auxiliary experiments from which the desired inferences can be obtained.